# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WikiMedia' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WikiMedia
  pod 'Alamofire', '~>4.7'
  pod 'AlamofireImage'
  pod 'ObjectMapper', '~>3.2'

  target 'WikiMediaTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'WikiMediaUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
